### ISSUE TITLE
Change to full logos

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/smo-wiki#16]
Use PNG generated from vector-graphic instead of JPG

**Comment by FlxVctr** [comment]
At the moment the logos appear pretty pixelated on mobile

**Comment by FlxVctr** [comment]
Files are in team KB folder

**Comment by Khandoker09** [comment]
keybase://team/fgz_smo/Style/FGZ_Styleguide_2020.pdf    is this the file location ?

**Comment by Khandoker09** [comment]
added all the png logos and create a pull request
