### ISSUE TITLE
Dropdown elements

### ISSUE THREAD

**Issue by kerosafr** [Leibniz-HBI/SMO-Wiki#26]
replace headings of single data analysis tools with dropdown headings

**Comment by FlxVctr** [comment]
transferred to the wiki repo

**Comment by kerosafr** [comment]
adjust the other "data analysis tool pages" with their implemented drowpdown headings in the pretty version

**Comment by FlxVctr** [comment]
Done. Kannst du schauen, ob alles so aussieht, wie es soll?

Hier ist eine Übersicht, was alles geändert wurde: https://github.com/Leibniz-HBI/smo-wiki/commit/010a8f3e19e137ed240cf14ce00793bf3a778446

**Comment by FlxVctr** [comment]
Wenn alles passt, kann das issue geschlossen werden
