### ISSUE TITLE
Add data  explore to visualization tools 

### ISSUE THREAD

**Issue by Khandoker09** [Leibniz-HBI/smo-wiki#30]
- https://snapcraft.io/dataexplore

**Comment by FlxVctr** [comment]
I don't understand, have you added it yet?

**Comment by Khandoker09** [comment]
https://docs.google.com/document/d/1WexRczcGdgvtNa7oZZXQqn4pIhYPQ0-BhhnO1JWj8yY/edit#

**Comment by FlxVctr** [comment]
Cool, thanks I added some comments and edits. Please update accordingly and reassign to me.

**Comment by Khandoker09** [comment]
Thank you for your comments , I fix it according to your suggestions

**Comment by FlxVctr** [comment]
This looks good now! Maybe add a screenshot and add it to the wiki, then assign back for a last check. Thank you!

**Comment by vomJupiter** [comment]
description for Data Explore is missing in the wiki article. Did you already write one?

**Comment by FlxVctr** [comment]
See GDocs Link above (send me your Google Doc Email on Keybase for access)
