### ISSUE TITLE
Export FROG tool added in section Telegram tools to 'pretty' wiki

### ISSUE THREAD

**Issue by FlorianPrimig** [Leibniz-HBI/SMO-Wiki#61]
I've added the FROG telegram data sampling software to the list of available API tools. I think it would be good to also export that addition to the 'pretty' wiki, soon.

**Comment by FlxVctr** [comment]
Thanks for your contribution! It really looks like a very helpful addition. I've updated the pretty version.

Also: You're now on our Wall of Fame (https://smo-wiki.leibniz-hbi.de/Wall-of-Fame) 🎉
(just some script evaluating git reports, in case you're wondering)
